// This file is auto-generated by `pnpm db:gen-types`.
// Do not edit manually.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
